modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0"
[[mods]] #mandatory
modId="gentlepicking" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Gentle Picking" #mandatory

logoFile="icon.png" #optional
credits="Shunupbups for the Fabric version" #optional
# A text field displayed in the mod UI
authors="Shunupbups, Lilypuree" #optional
description='''
A simple mod which lets you pick up flowers or mushrooms with a right click! Requested by MoonlitLamps.
Blocks that can be 'picked' are decided by the gentlepicking:pickable block tag.'''

[[dependencies.gentlepicking]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
